//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppliWSTEST.Tests.WebAppliWSTESTReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://localhost/WebAppliWSTEST/", ConfigurationName="WebAppliWSTESTReference.WebServiceTestSoap")]
    public interface WebServiceTestSoap {
        
        // CODEGEN: Generating message contract since element name FibonacciResult from namespace http://localhost/WebAppliWSTEST/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/WebAppliWSTEST/Fibonacci", ReplyAction="*")]
        WebAppliWSTEST.Tests.WebAppliWSTESTReference.FibonacciResponse Fibonacci(WebAppliWSTEST.Tests.WebAppliWSTESTReference.FibonacciRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/WebAppliWSTEST/Fibonacci", ReplyAction="*")]
        System.Threading.Tasks.Task<WebAppliWSTEST.Tests.WebAppliWSTESTReference.FibonacciResponse> FibonacciAsync(WebAppliWSTEST.Tests.WebAppliWSTESTReference.FibonacciRequest request);
        
        // CODEGEN: Generating message contract since element name xml from namespace http://localhost/WebAppliWSTEST/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/WebAppliWSTEST/XmlToJson", ReplyAction="*")]
        WebAppliWSTEST.Tests.WebAppliWSTESTReference.XmlToJsonResponse XmlToJson(WebAppliWSTEST.Tests.WebAppliWSTESTReference.XmlToJsonRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/WebAppliWSTEST/XmlToJson", ReplyAction="*")]
        System.Threading.Tasks.Task<WebAppliWSTEST.Tests.WebAppliWSTESTReference.XmlToJsonResponse> XmlToJsonAsync(WebAppliWSTEST.Tests.WebAppliWSTESTReference.XmlToJsonRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FibonacciRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Fibonacci", Namespace="http://localhost/WebAppliWSTEST/", Order=0)]
        public WebAppliWSTEST.Tests.WebAppliWSTESTReference.FibonacciRequestBody Body;
        
        public FibonacciRequest() {
        }
        
        public FibonacciRequest(WebAppliWSTEST.Tests.WebAppliWSTESTReference.FibonacciRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost/WebAppliWSTEST/")]
    public partial class FibonacciRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int number;
        
        public FibonacciRequestBody() {
        }
        
        public FibonacciRequestBody(int number) {
            this.number = number;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FibonacciResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FibonacciResponse", Namespace="http://localhost/WebAppliWSTEST/", Order=0)]
        public WebAppliWSTEST.Tests.WebAppliWSTESTReference.FibonacciResponseBody Body;
        
        public FibonacciResponse() {
        }
        
        public FibonacciResponse(WebAppliWSTEST.Tests.WebAppliWSTESTReference.FibonacciResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost/WebAppliWSTEST/")]
    public partial class FibonacciResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string FibonacciResult;
        
        public FibonacciResponseBody() {
        }
        
        public FibonacciResponseBody(string FibonacciResult) {
            this.FibonacciResult = FibonacciResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class XmlToJsonRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="XmlToJson", Namespace="http://localhost/WebAppliWSTEST/", Order=0)]
        public WebAppliWSTEST.Tests.WebAppliWSTESTReference.XmlToJsonRequestBody Body;
        
        public XmlToJsonRequest() {
        }
        
        public XmlToJsonRequest(WebAppliWSTEST.Tests.WebAppliWSTESTReference.XmlToJsonRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost/WebAppliWSTEST/")]
    public partial class XmlToJsonRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string xml;
        
        public XmlToJsonRequestBody() {
        }
        
        public XmlToJsonRequestBody(string xml) {
            this.xml = xml;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class XmlToJsonResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="XmlToJsonResponse", Namespace="http://localhost/WebAppliWSTEST/", Order=0)]
        public WebAppliWSTEST.Tests.WebAppliWSTESTReference.XmlToJsonResponseBody Body;
        
        public XmlToJsonResponse() {
        }
        
        public XmlToJsonResponse(WebAppliWSTEST.Tests.WebAppliWSTESTReference.XmlToJsonResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost/WebAppliWSTEST/")]
    public partial class XmlToJsonResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string XmlToJsonResult;
        
        public XmlToJsonResponseBody() {
        }
        
        public XmlToJsonResponseBody(string XmlToJsonResult) {
            this.XmlToJsonResult = XmlToJsonResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceTestSoapChannel : WebAppliWSTEST.Tests.WebAppliWSTESTReference.WebServiceTestSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceTestSoapClient : System.ServiceModel.ClientBase<WebAppliWSTEST.Tests.WebAppliWSTESTReference.WebServiceTestSoap>, WebAppliWSTEST.Tests.WebAppliWSTESTReference.WebServiceTestSoap {
        
        public WebServiceTestSoapClient() {
        }
        
        public WebServiceTestSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceTestSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceTestSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceTestSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebAppliWSTEST.Tests.WebAppliWSTESTReference.FibonacciResponse WebAppliWSTEST.Tests.WebAppliWSTESTReference.WebServiceTestSoap.Fibonacci(WebAppliWSTEST.Tests.WebAppliWSTESTReference.FibonacciRequest request) {
            return base.Channel.Fibonacci(request);
        }
        
        public string Fibonacci(int number) {
            WebAppliWSTEST.Tests.WebAppliWSTESTReference.FibonacciRequest inValue = new WebAppliWSTEST.Tests.WebAppliWSTESTReference.FibonacciRequest();
            inValue.Body = new WebAppliWSTEST.Tests.WebAppliWSTESTReference.FibonacciRequestBody();
            inValue.Body.number = number;
            WebAppliWSTEST.Tests.WebAppliWSTESTReference.FibonacciResponse retVal = ((WebAppliWSTEST.Tests.WebAppliWSTESTReference.WebServiceTestSoap)(this)).Fibonacci(inValue);
            return retVal.Body.FibonacciResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebAppliWSTEST.Tests.WebAppliWSTESTReference.FibonacciResponse> WebAppliWSTEST.Tests.WebAppliWSTESTReference.WebServiceTestSoap.FibonacciAsync(WebAppliWSTEST.Tests.WebAppliWSTESTReference.FibonacciRequest request) {
            return base.Channel.FibonacciAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebAppliWSTEST.Tests.WebAppliWSTESTReference.FibonacciResponse> FibonacciAsync(int number) {
            WebAppliWSTEST.Tests.WebAppliWSTESTReference.FibonacciRequest inValue = new WebAppliWSTEST.Tests.WebAppliWSTESTReference.FibonacciRequest();
            inValue.Body = new WebAppliWSTEST.Tests.WebAppliWSTESTReference.FibonacciRequestBody();
            inValue.Body.number = number;
            return ((WebAppliWSTEST.Tests.WebAppliWSTESTReference.WebServiceTestSoap)(this)).FibonacciAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebAppliWSTEST.Tests.WebAppliWSTESTReference.XmlToJsonResponse WebAppliWSTEST.Tests.WebAppliWSTESTReference.WebServiceTestSoap.XmlToJson(WebAppliWSTEST.Tests.WebAppliWSTESTReference.XmlToJsonRequest request) {
            return base.Channel.XmlToJson(request);
        }
        
        public string XmlToJson(string xml) {
            WebAppliWSTEST.Tests.WebAppliWSTESTReference.XmlToJsonRequest inValue = new WebAppliWSTEST.Tests.WebAppliWSTESTReference.XmlToJsonRequest();
            inValue.Body = new WebAppliWSTEST.Tests.WebAppliWSTESTReference.XmlToJsonRequestBody();
            inValue.Body.xml = xml;
            WebAppliWSTEST.Tests.WebAppliWSTESTReference.XmlToJsonResponse retVal = ((WebAppliWSTEST.Tests.WebAppliWSTESTReference.WebServiceTestSoap)(this)).XmlToJson(inValue);
            return retVal.Body.XmlToJsonResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebAppliWSTEST.Tests.WebAppliWSTESTReference.XmlToJsonResponse> WebAppliWSTEST.Tests.WebAppliWSTESTReference.WebServiceTestSoap.XmlToJsonAsync(WebAppliWSTEST.Tests.WebAppliWSTESTReference.XmlToJsonRequest request) {
            return base.Channel.XmlToJsonAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebAppliWSTEST.Tests.WebAppliWSTESTReference.XmlToJsonResponse> XmlToJsonAsync(string xml) {
            WebAppliWSTEST.Tests.WebAppliWSTESTReference.XmlToJsonRequest inValue = new WebAppliWSTEST.Tests.WebAppliWSTESTReference.XmlToJsonRequest();
            inValue.Body = new WebAppliWSTEST.Tests.WebAppliWSTESTReference.XmlToJsonRequestBody();
            inValue.Body.xml = xml;
            return ((WebAppliWSTEST.Tests.WebAppliWSTESTReference.WebServiceTestSoap)(this)).XmlToJsonAsync(inValue);
        }
    }
}
